name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1